[tox]
envlist = unittest, quality
requires =
    tox-uv>=1

[testenv]
runner = uv-venv-lock-runner

[testenv:unittest]
dependency_groups = test
commands =
    coverage run -m pytest src/ccx_keys/tests
    coverage report -m
    coverage xml

[testenv:quality]
dependency_groups = quality
commands =
    pycodestyle --config=.pep8 src/ccx_keys
    pylint --rcfile=pylintrc src/ccx_keys
